 # @param {string} vm_name Name of the VM
vm_name: my-test-virtual-machine-greenops

# @param {number} cpu  Number of CPU cores
cpu: 2

# @param {number} memory Number of GB of RAM
memory: 2

 # @param {enum{azure,aws,gcp}} provider Public cloud provider
provider: azure

# @param {object} scheduling VM assigned scheduling
scheduling:
  # @param {pattern{^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$}} time Designated time of scheduling (ISO 8601 formatted date string in UTC)
  time: 2024-11-21T10:00:00Z
  
  # @param {string} location Designated location of scheduling
  location: italynorth



# temporary values for the Azure provider
# later they will be moved to the azure_values.yaml file
# and imported using .Files.Get
azure:
  provisioningTimeOffset: 300

  resourceGroup:
    armId: ""

  virtualNetwork:
    name: samplevnet
    addressSpace:
      addressPrefixes:
        - 10.0.0.0/16

  virtualNetworkSubnet:
    name: samplesubnet
    addressPrefixes: 10.0.0.0/24

  networkInterface:
    name: samplenic
    ipConfigurations:
      - name: ipconfig1
        privateIPAllocationMethod: Dynamic
        subnet:
          reference:
            group: network.azure.com
            kind: VirtualNetworksSubnet
            name: samplesubnet

  virtualMachine:
    hardwareProfile:
      vmSize: Standard_DS1_v2
    networkProfile:
      networkInterfaces:
      - reference:
          group: network.azure.com
          kind: NetworkInterface
          name: samplenic
    osProfile:
      adminPassword:
        key: password
        name: greenops-vm-secret
      adminUsername: adminuser
      computerName: poppy
    storageProfile:
      imageReference:
        publisher: Canonical
        offer: 0001-com-ubuntu-server-jammy
        sku: 22_04-lts
        version: latest
