{{- $av := (.Files.Get "azure_values.yaml") | fromYaml }}
apiVersion: network.azure.com/v1api20240301
kind: NetworkInterface
metadata:
  name: {{ $av.networkInterface.name }}
spec:
  location: {{ .Values.schedulingLocation }}
  owner:
    armId: {{ $av.resourceGroup.armId }}
  ipConfigurations: {{ $av.networkInterface.ipConfigurations | toYaml | nindent 4 }}
