apiVersion: compute.azure.com/v1api20220301
kind: VirtualMachine
metadata:
  name: {{ .Values.name }}
spec:
  hardwareProfile:
    vmSize: Standard_DS1_v2
  location: {{ .Values.schedulingLocation }}
  networkProfile:
    networkInterfaces:
    - reference:
        group: network.azure.com
        kind: NetworkInterface
        name: samplenic
  osProfile:
    adminPassword:
      key: password
      name: greenops-vm-secret
    adminUsername: adminuser
    computerName: poppy 
  owner:
     armId: '/subscriptions/31a6f7f0-996a-490e-b431-25c3f54b08b5/resourceGroups/UNITN'
  storageProfile:
    imageReference:
      publisher: Canonical
      offer: 0001-com-ubuntu-server-jammy
      sku: 22_04-lts
      version: latest
