{{- $av := (.Files.Get "azure_values.yaml") | fromYaml }}
apiVersion: network.azure.com/v1api20240301
kind: VirtualNetwork
metadata:
  name: {{ $av.virtualNetwork.name }}
spec:
  location: {{ .Values.schedulingLocation }}
  owner:
    armId: {{ $av.resourceGroup.armId }}
  addressSpace: {{ $av.virtualNetwork.addressSpace | toYaml | nindent 4 }}

