{{ $av := (.Files.Get "azure_values.yaml") | fromYaml }}
{{ $aiv := (.Files.Get "azure_instances_values.yaml") | fromYaml }}

apiVersion: compute.azure.com/v1api20220301
kind: VirtualMachine
metadata:
  name: {{ .Values.vmName }}
  namespace: {{ .Values.namespace | default "greenops" }}
spec:
  hardwareProfile:
    vmSize: Standard_DS1_v2
  location: {{ .Values.schedulingLocation }}
  networkProfile: {{ $av.virtualMachine.networkProfile | toYaml | nindent 4 }}
  osProfile: {{ $av.virtualMachine.osProfile | toYaml | nindent 4 }}
  owner:
    armId: {{ $av.resourceGroup.armId }}
  storageProfile: {{ $av.virtualMachine.storageProfile | toYaml | nindent 4 }}
