{{- $av := (.Files.Get "azure_values.yaml") | fromYaml }}
apiVersion: network.azure.com/v1api20240301
kind: VirtualNetworksSubnet
metadata:
  name: {{ $av.virtualNetworkSubnet.name }}
spec:
  owner:
    name: {{ $av.virtualNetwork.name }}
  addressPrefix: {{ $av.virtualNetworkSubnet.addressPrefixes }}
