{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now }}
{{ if $now.After $schedulingTime }}
{{- $av := (.Files.Get "azure_values.yaml") | fromYaml }}
apiVersion: network.azure.com/v1api20240301
kind: VirtualNetworksSubnet
metadata:
  name: {{ $av.virtualNetworkSubnet.name }}
spec:
  owner:
    name: {{ $av.virtualNetwork.name }}
  addressPrefix: {{ $av.virtualNetworkSubnet.addressPrefixes }}
{{ end }}
