{{ if hasKey .Values "provider" }}
{{ $provider := .Values.provider }}
{{ if eq $provider "azure" }}
{{ if hasKey .Values "schedulingTime" }}
{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now | date "2006-01-02T15:04:05Z" }}
{{ if $now.After $schedulingTime }}
{{- $av := (.Files.Get "azure_values.yaml") | fromYaml }}
apiVersion: network.azure.com/v1api20240301
kind: VirtualNetworksSubnet
metadata:
  name: {{ .Values.vmName }}-{{ $av.virtualNetworkSubnet.suffix }}
  namespace: {{ .Values.namespace | default "greenops" }}
spec:
  owner:
    name: {{ .Values.vmName }}-{{ $av.virtualNetwork.suffix }}
  addressPrefixes: {{ $av.virtualNetworkSubnet.addressPrefixes }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}