apiVersion: network.azure.com/v1api20240301
kind: VirtualNetworksSubnet
metadata:
  name: samplesubnet
  namespace: {{ .Values.namespace | default "greenops" }}
spec:
  owner:
    name: samplevnet
  addressPrefixes: 10.0.0.0/24