{{ if hasKey .Values "provider" }}
{{ $provider := .Values.provider }}
{{ if eq $provider "aws" }}

{{ if hasKey .Values "schedulingTime" }}
{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now }}
{{ if $now.After $schedulingTime }}

{{ $aiv := (.Files.Get "aws/aws_instances_values.yaml") | fromYaml }}
{{ $req := dict "cpu" .Values.cpu "memory" .Values.memory "vmSizes" $aiv.awsVmSizes "defaultVmSize" $aiv.awsVmSizeDefault }}
{{- $vmSize := include "findBestVmSize" $req -}}

{{- $os := .Values.os | default "ubuntu" -}}
{{- $osVersion := .Values.osVersion | default "24.04 LTS" -}}
{{- $amiData := (.Files.Get "aws/aws_ami.yaml") | fromYaml }}
{{- $imageID := include "getAMI" (list .Values.schedulingLocation $os $osVersion $amiData) -}}

# https://github.com/aws-controllers-k8s/ec2-controller/blob/main/test/e2e/resources/vpc.yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Instance
metadata:
  name: {{ .Values.vmName }}
  namespace: {{ .Values.namespace | default "greenops" }}
  annotations:
    services.k8s.aws/region: {{ .Values.schedulingLocation }}
spec:
  imageID: {{ $imageID }}
  instanceType: {{ $vmSize }}
  # https://aws-controllers-k8s.github.io/community/docs/tutorials/ec2-example/#validate
  # probably here we need helm lookup functions to get the subnet ID
  subnetID: "test"
  tags:
    - key: project
      value: greenops

{{ end }}
{{ end }}
{{ end }}
{{ end }}
