apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Subnet
metadata:
  name: $SUBNET_NAME
  namespace: $INSTANCE_NAMESPACE
  annotations:
    services.k8s.aws/region: $REGION
spec:
  cidrBlock: "10.0.1.0/24"
  vpcRef: 
    from: 
      name: string
      namespace: string
  tags:
    - key: $TAG_KEY
      value: $TAG_VALUE