apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPC
metadata:
  name: $
  namespace: $INSTANCE_NAMESPACE
  annotations:
    services.k8s.aws/region: $REGION
spec:
  cidrBlocks: 
  - "10.0.0.0/16"
  enableDNSSupport: false
  enableDNSHostnames: false
  tags:
    - key: testKey
      value: testValue