{{ if hasKey .Values "provider" }}
{{ $provider := .Values.provider }}
{{ if eq $provider "gcp" }}
{{ if hasKey .Values "schedulingTime" }}
{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now }}
{{ if $now.After $schedulingTime }}

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: {{ .Values.vmName }}-network
  namespace: {{ .Values.namespace | default "greenops" }}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false

{{ end }}
{{ end }}
{{ end }}
{{ end }}
