{{ if hasKey .Values "provider" }}
{{ $provider := .Values.provider }}
{{ if eq $provider "gcp" }}
{{ if hasKey .Values "schedulingTime" }}
{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now }}
{{ if $now.After $schedulingTime }}

{{- $regionZoneMap := (.Files.Get "gcp/gcp_region_zone_map.yaml") | fromYaml -}}
{{- $zone := include "getZone" (list $regionZoneMap .Values.schedulingLocation .Values.vmName) -}}

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: {{ .Values.vmName }}-disk
  namespace: {{ .Values.namespace | default "greenops" }}
spec:
  physicalBlockSizeBytes: 4096
  size: 1
  type: pd-ssd
  location: {{ $zone }}

{{ end }}
{{ end }}
{{ end }}
{{ end }}
