{{ if hasKey .Values "provider" }}
{{ $provider := .Values.provider }}
{{ if eq $provider "gcp" }}
{{ if hasKey .Values "schedulingTime" }}
{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now }}
{{ if $now.After $schedulingTime }}

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: {{ .Values.vmName }}-disk
  namespace: {{ .Values.namespace | default "greenops" }}
spec:
  physicalBlockSizeBytes: 4096
  size: 1
  type: pd-ssd
  location: {{ .Values.schedulingLocation | default "europe-west8" }} # europe-west8 is the region for Milan

{{ end }}
{{ end }}
{{ end }}
{{ end }}
