{{ if hasKey .Values "provider" }}
{{ $provider := .Values.provider }}
{{ if eq $provider "gcp" }}
{{ if hasKey .Values "schedulingTime" }}
{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now }}
{{ if $now.After $schedulingTime }}

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: {{ .Values.vmName }}-subnetwork
  namespace: {{ .Values.namespace | default "greenops" }}
spec:
  networkRef:
    name: {{ .Values.vmName }}-network
  ipCidrRange: 10.2.0.0/16
  region: {{ .Values.schedulingLocation | default "europe-west8" }}
  secondaryIpRange:
    - rangeName: cloudrange
      ipCidrRange: 10.3.16.0/20

{{ end }}
{{ end }}
{{ end }}
{{ end }}
