{{ if hasKey .Values "provider" }}
{{ $provider := .Values.provider }}
{{ if eq $provider "gcp" }}
{{ if hasKey .Values "schedulingTime" }}
{{ $schedulingTime := .Values.schedulingTime | toDate "2006-01-02T15:04:05Z" }}
{{ $now := now }}
{{ if $now.After $schedulingTime }}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .Values.vmName }}-serviceaccount
  namespace: {{ .Values.namespace | default "greenops" }}
  
{{ end }}
{{ end }}
{{ end }}
{{ end }}
