# Source: https://cloud-images.ubuntu.com/locator/ec2/
amis:
  us-west-1:
    - ami: ami-07d2649d67dbe8900
      os: ubuntu
      name: "Noble Numbat"
      version: "24.04 LTS"
      arch: "amd64"
      instance_type: "hvm:ebs-ssd-gp3"
      release: "20250115"
      aki: "hvm"
    - ami: ami-0d413c682033e11fd
      os: ubuntu
      name: "Jammy Jellyfish"
      version: "22.04 LTS"
      arch: "amd64"
      instance_type: "hvm:ebs-ssd"
      release: "20250112"
      aki: "hvm"
  us-east-1:
    - ami: ami-04b4f1a9cf54c11d0
      os: ubuntu
      name: "Noble Numbat"
      version: "24.04 LTS"
      arch: "amd64"
      instance_type: "hvm:ebs-ssd-gp3"
      release: "20250115"
      aki: "hvm"
    - ami: ami-0e1bed4f06a3b463d
      os: ubuntu
      name: "Jammy Jellyfish"
      version: "22.04 LTS"
      arch: "amd64"
      instance_type: "hvm:ebs-ssd"
      release: "20250112"
      aki: "hvm"
  ap-southeast-1:
    - ami: ami-0672fd5b9210aa093
      os: ubuntu
      name: "Noble Numbat"
      version: "24.04 LTS"
      arch: "amd64"
      instance_type: "hvm:ebs-ssd-gp3"
      release: "20250115"
      aki: "hvm"
    - ami: ami-0198a868663199764
      os: ubuntu
      name: "Jammy Jellyfish"
      version: "22.04 LTS"
      arch: "amd64"
      instance_type: "hvm:ebs-ssd"
      release: "20250112"
      aki: "hvm"
# ... continuing for all regions ...