{{ $provider := .Values.provider }}
{{ if eq $provider "azure" }}
{{ $now := now }}
{{ $schedulingTime := .Values.scheduling.time | toDate "2006-01-02T15:04:05Z" }}
{{ if $now.After $schedulingTime }}
apiVersion: network.azure.com/v1api20240301
kind: VirtualNetwork
metadata:
  name: {{ .Values.azure.virtualNetwork.name }}
spec:
  location: {{ .Values.scheduling.location }}
  owner:
    armId: {{ .Values.azure.resourceGroup.armId }}
  addressSpace: {{ .Values.azure.virtualNetwork.addressSpace | toYaml | nindent 4 }}
{{ end }}
{{ end }}